from __future__ import annotations

import csv
import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "scripts" / "reconstruct.py"
CONFIG = ROOT / "data" / "curation" / "reconstruction-50pct.json"


class FiftyPercentReconstructionTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.temp = tempfile.TemporaryDirectory()
        cls.output = Path(cls.temp.name)
        (cls.output / "unrelated-preview.pdf").write_bytes(b"not generated by reconstruction")
        subprocess.run(
            [sys.executable, str(SCRIPT), "--config", str(CONFIG), "--output", str(cls.output)],
            check=True,
            capture_output=True,
            text=True,
        )
        cls.report = json.loads((cls.output / "verification_report.json").read_text())

    @classmethod
    def tearDownClass(cls) -> None:
        cls.temp.cleanup()

    def test_first_50_percent_crossing_is_verified(self) -> None:
        cutoff = self.report["data_cutoff"]
        self.assertEqual(cutoff["status"], "confirmed")
        self.assertEqual(cutoff["submission_id"], "8e9c9a2")
        self.assertEqual(
            cutoff["source_commit"],
            "60d61859fa6965eba53634f91877b1141a6f9dce",
        )
        self.assertTrue(cutoff["first_crossing_verified"])
        self.assertTrue(cutoff["data_cutoff_covers_final_api_update"])
        self.assertGreater(cutoff["best_promoted_score_before_crossing"], cutoff["threshold_score"])
        self.assertEqual(cutoff["cutoff_metrics"]["qt"], 1_495_670_403)

    def test_population_is_pinned_and_score_consistent(self) -> None:
        snapshot = self.report["api_response"]
        self.assertEqual(snapshot["raw_rows"], 831)
        self.assertEqual(snapshot["raw_rows_at_data_cutoff"], 826)
        self.assertEqual(snapshot["metric_rows_at_data_cutoff"], 576)
        self.assertEqual(snapshot["pre_cut_rows_updated_after_cut"], 0)
        self.assertTrue(snapshot["all_metric_scores_equal_q_times_t"])

    def test_pareto_sets_match_the_pinned_expectations(self) -> None:
        api = self.report["pinned_response_api_metrics_pareto"]
        notes = self.report["note_rule_sensitivity"]
        paper = self.report["paper_admitted_pareto"]
        self.assertTrue(api["matches_pinned_expectation"])
        self.assertEqual(len(api["actual_ids"]), 15)
        self.assertTrue(notes["matches_pinned_expectation"])
        self.assertEqual(len(notes["pareto_ids"]), 16)
        self.assertTrue(paper["matches_configured_expectation"])
        self.assertEqual(len(paper["actual_ids"]), 8)

    def test_transition_selection_is_manifest_selected_and_includes_cutoff(self) -> None:
        transition = self.report["transition_slice"]
        self.assertEqual(transition["count"], 15)
        self.assertTrue(transition["within_selected_display_range"])
        self.assertIn("8e9c9a2", transition["ids"])

    def test_main_figure_uses_paper_admission_rule(self) -> None:
        svg = (self.output / "frontier_figure_paper.svg").read_text()
        self.assertIn("8 admitted Pareto points", svg)
        self.assertIn("admitted Pareto set", svg)
        self.assertNotIn("API-metric Pareto", svg)

    def test_pareto_manifest_identifies_the_eight_paper_points(self) -> None:
        with (self.output / "pareto_manifest.csv").open(newline="") as handle:
            rows = list(csv.DictReader(handle))
        self.assertEqual(
            [row["submission"] for row in rows],
            [
                "b6f2b0a",
                "f1d8707",
                "39a9b5f",
                "a3b0148",
                "4352cfb",
                "1c0e0e9",
                "8e9c9a2",
                "a536a48",
            ],
        )
        self.assertTrue(all(row["source_commit"] for row in rows))

    def test_manifest_lists_only_declared_generated_outputs(self) -> None:
        manifest = json.loads((self.output / "source_manifest.json").read_text())
        self.assertNotIn("unrelated-preview.pdf", manifest["outputs"])
        self.assertIn("frontier_figure_paper.pdf", manifest["outputs"])
        self.assertIn(
            "scripts/verify_paper_integration.py",
            manifest["implementation"],
        )
        self.assertIn(
            "tests/test_50pct_reconstruction.py",
            manifest["implementation"],
        )
        self.assertNotIn("manuscript_artifacts", manifest)


if __name__ == "__main__":
    unittest.main()
